### ISSUE TITLE
Firefox: Redirecting to external URL displays disconnection warning

### ISSUE THREAD

**Issue by joozek78** [Palindrom/palindrom-redirect#3]
1. use code like this: `<link is="puppet-redirect" url$="{{model.RedirectUrl$}}" />`
2. change `RedirectUrl` to external URL (e.g. starcounter.io) from code-behind
3. a modal shows briefly ("Connection error, please reload page!")
4. redirection takes place after about 1 second
5. using URL from the same SPA didn't reproduce the bug

**Comment by warpech** [comment]
This is actually not related to puppet-redirect, but to PuppetJs. 

Firefox displays WebSocket disconnection alert when you are going from PuppetJs page to some other page.

**Comment by warpech** [comment]
Moved to https://github.com/Palindrom/Palindrom/issues/160
